import type {
  AppNotification,
  Chat,
  Listing,
  Nonprofit,
  Report,
  Transaction,
  User,
} from "@/types";

export const users: User[] = [
  {
    id: "u_me",
    name: "Alex Rivera",
    city: "Dallas, TX",
    bio: "Decluttering with purpose. SMU grad, runner, plant hoarder.",
    avatarColor: "#115E59",
    initials: "AR",
    verifiedEmail: true,
    verifiedPhone: true,
    completedTransactions: 14,
    donatedCents: 62300,
    rating: 4.9,
    ratingCount: 13,
    joinedAt: "2025-09-02",
  },
  {
    id: "u_maya",
    name: "Maya Chen",
    city: "Dallas, TX",
    bio: "Furniture flipper turned donor.",
    avatarColor: "#E76F51",
    initials: "MC",
    verifiedEmail: true,
    verifiedPhone: true,
    completedTransactions: 31,
    donatedCents: 154000,
    rating: 5.0,
    ratingCount: 28,
    joinedAt: "2025-06-14",
  },
  {
    id: "u_jordan",
    name: "Jordan Blake",
    city: "Plano, TX",
    bio: "Books, vinyl, and good causes.",
    avatarColor: "#0F172A",
    initials: "JB",
    verifiedEmail: true,
    verifiedPhone: false,
    completedTransactions: 6,
    donatedCents: 21800,
    rating: 4.7,
    ratingCount: 5,
    joinedAt: "2026-01-20",
  },
  {
    id: "u_sam",
    name: "Sam Okafor",
    city: "Irving, TX",
    avatarColor: "#15803D",
    initials: "SO",
    verifiedEmail: true,
    verifiedPhone: true,
    completedTransactions: 19,
    donatedCents: 88400,
    rating: 4.8,
    ratingCount: 17,
    joinedAt: "2025-11-03",
  },
];

export const currentUser = users[0];

export const nonprofits: Nonprofit[] = [
  {
    id: "n_habitat",
    name: "Habitat for Humanity DFW",
    ein: "75-1234567",
    mission: "Building homes, communities and hope across North Texas.",
    about:
      "We bring people together to build homes, communities and hope. Every donation funds local builds in Dallas-Fort Worth.",
    website: "habitatdfw.org",
    category: "community",
    city: "Dallas",
    state: "TX",
    logoColor: "#115E59",
    initials: "HH",
    verification: "approved",
    sponsored: true,
    raisedCents: 482000,
    supporters: 312,
  },
  {
    id: "n_paws",
    name: "Dallas Paws Rescue",
    ein: "75-2345678",
    mission: "Rescuing and rehoming animals in need.",
    about:
      "A no-kill shelter providing medical care, foster homes, and adoption services for abandoned animals.",
    website: "dallaspaws.org",
    category: "animals",
    city: "Dallas",
    state: "TX",
    logoColor: "#E76F51",
    initials: "DP",
    verification: "approved",
    sponsored: true,
    raisedCents: 219400,
    supporters: 188,
  },
  {
    id: "n_readdfw",
    name: "Read DFW",
    ein: "75-3456789",
    mission: "Childhood literacy for every kid in North Texas.",
    about:
      "We put books in the hands of children and run after-school reading programs across underserved neighborhoods.",
    website: "readdfw.org",
    category: "education",
    city: "Fort Worth",
    state: "TX",
    logoColor: "#0F172A",
    initials: "RD",
    verification: "approved",
    sponsored: false,
    raisedCents: 134900,
    supporters: 96,
  },
  {
    id: "n_green",
    name: "Trinity River Conservancy",
    ein: "75-4567890",
    mission: "Protecting and restoring the Trinity River watershed.",
    about:
      "Native planting, cleanups, and habitat restoration along the Trinity River corridor.",
    website: "trinityriver.org",
    category: "environment",
    city: "Dallas",
    state: "TX",
    logoColor: "#15803D",
    initials: "TR",
    verification: "approved",
    sponsored: false,
    raisedCents: 97200,
    supporters: 74,
  },
  {
    id: "n_health",
    name: "North Texas Free Clinic",
    ein: "75-5678901",
    mission: "Healthcare access for the uninsured.",
    about:
      "Free primary care, dental, and mental health services for low-income families.",
    website: "ntfreeclinic.org",
    category: "health",
    city: "Garland",
    state: "TX",
    logoColor: "#DC2626",
    initials: "NT",
    verification: "approved",
    sponsored: false,
    raisedCents: 61500,
    supporters: 53,
  },
  {
    id: "n_arts",
    name: "Dallas Youth Arts Collective",
    ein: "75-6789012",
    mission: "Free art and music education for teens.",
    about:
      "Studios, instruments, and mentorship that keep creativity alive after school.",
    website: "dyac.org",
    category: "arts",
    city: "Dallas",
    state: "TX",
    logoColor: "#E08A1E",
    initials: "YA",
    verification: "pending",
    sponsored: false,
    raisedCents: 0,
    supporters: 0,
  },
];

export const listings: Listing[] = [
  {
    id: "l_bike",
    sellerId: "u_maya",
    title: "Vintage Schwinn Road Bike",
    description:
      "1980s Schwinn World Sport, recently tuned. New tires and brake pads. A classic steel-frame ride that just needs a new home. Smoke-free garage storage.",
    category: "sports",
    imageColor: "#115E59",
    city: "Dallas, TX",
    pickupArea: "Lower Greenville",
    condition: "good",
    priceCents: 12000,
    nonprofitId: "n_habitat",
    status: "active",
    createdAt: "2026-05-28T14:00:00Z",
  },
  {
    id: "l_sofa",
    sellerId: "u_sam",
    title: "Mid-Century Walnut Sofa",
    description:
      "Three-seater with original walnut legs. One small scuff on the back (photo). Extremely comfortable, pet-free home.",
    category: "furniture",
    imageColor: "#E76F51",
    city: "Irving, TX",
    pickupArea: "Las Colinas",
    condition: "like_new",
    priceCents: 38000,
    nonprofitId: "n_paws",
    status: "active",
    createdAt: "2026-05-29T09:30:00Z",
  },
  {
    id: "l_camera",
    sellerId: "u_jordan",
    title: "Canon AE-1 Film Camera",
    description:
      "Iconic 35mm SLR with 50mm f/1.8 lens. Fully working, light seals replaced last year. Includes original strap.",
    category: "electronics",
    imageColor: "#0F172A",
    city: "Plano, TX",
    pickupArea: "Downtown Plano",
    condition: "good",
    priceCents: 22000,
    nonprofitId: "n_readdfw",
    status: "interested",
    createdAt: "2026-05-30T17:45:00Z",
  },
  {
    id: "l_books",
    sellerId: "u_me",
    title: "Box of Classic Novels (40+)",
    description:
      "Penguin Classics paperbacks, mostly excellent condition. Steinbeck, Austen, Baldwin, more. Perfect for a classroom or little free library.",
    category: "books",
    imageColor: "#15803D",
    city: "Dallas, TX",
    pickupArea: "Bishop Arts",
    condition: "good",
    priceCents: 4500,
    nonprofitId: "n_readdfw",
    status: "active",
    createdAt: "2026-05-31T11:10:00Z",
  },
  {
    id: "l_guitar",
    sellerId: "u_maya",
    title: "Yamaha FG800 Acoustic Guitar",
    description:
      "Solid spruce top, great starter or backup guitar. Minor pick wear, plays beautifully. Comes with gig bag.",
    category: "music",
    imageColor: "#E08A1E",
    city: "Dallas, TX",
    pickupArea: "Deep Ellum",
    condition: "good",
    priceCents: 14000,
    nonprofitId: "n_arts",
    status: "active",
    createdAt: "2026-05-27T08:00:00Z",
  },
  {
    id: "l_desk",
    sellerId: "u_sam",
    title: "Standing Desk (Electric)",
    description:
      "Dual-motor sit/stand desk, 48x30 bamboo top. Memory presets work perfectly. Selling because I moved.",
    category: "furniture",
    imageColor: "#0B3D3A",
    city: "Irving, TX",
    pickupArea: "Valley Ranch",
    condition: "like_new",
    priceCents: 26000,
    nonprofitId: "n_green",
    status: "active",
    createdAt: "2026-05-26T15:20:00Z",
  },
  {
    id: "l_console",
    sellerId: "u_jordan",
    title: "Nintendo Switch + 3 Games",
    description:
      "Original model, great battery. Includes Mario Kart 8, Odyssey, and Zelda. Joy-cons drift-free.",
    category: "electronics",
    imageColor: "#DC2626",
    city: "Plano, TX",
    pickupArea: "Legacy West",
    condition: "good",
    priceCents: 18000,
    nonprofitId: "n_paws",
    status: "active",
    createdAt: "2026-05-31T19:00:00Z",
  },
  {
    id: "l_plant",
    sellerId: "u_me",
    title: "Monstera Deliciosa (Large)",
    description:
      "Healthy 4ft monstera in a terracotta pot. Too big for my apartment now. Local pickup only, it's heavy!",
    category: "home",
    imageColor: "#16A34A",
    city: "Dallas, TX",
    pickupArea: "Bishop Arts",
    condition: "good",
    priceCents: 3500,
    nonprofitId: "n_green",
    status: "active",
    createdAt: "2026-05-30T13:00:00Z",
  },
];

export const chats: Chat[] = [
  {
    id: "c_camera",
    listingId: "l_camera",
    buyerId: "u_me",
    sellerId: "u_jordan",
    lastActivity: "2026-06-01T10:20:00Z",
    messages: [
      {
        id: "m1",
        senderId: "system",
        content: "Alex expressed interest in “Canon AE-1 Film Camera”.",
        createdAt: "2026-05-31T18:00:00Z",
      },
      {
        id: "m2",
        senderId: "u_me",
        content: "Hi! Is the camera still available? Would $200 work?",
        createdAt: "2026-05-31T18:02:00Z",
      },
      {
        id: "m3",
        senderId: "u_jordan",
        content:
          "Hey Alex! Yes it is. I could do $200 if you can pick up in Downtown Plano this week.",
        createdAt: "2026-05-31T18:30:00Z",
      },
      {
        id: "m4",
        senderId: "u_me",
        content: "Perfect. How about Saturday around noon at the Plano Police HQ lot?",
        createdAt: "2026-06-01T10:18:00Z",
      },
      {
        id: "m5",
        senderId: "u_jordan",
        content: "Works for me. I'll mark it reserved for you.",
        createdAt: "2026-06-01T10:20:00Z",
      },
    ],
  },
  {
    id: "c_sofa",
    listingId: "l_sofa",
    buyerId: "u_me",
    sellerId: "u_sam",
    lastActivity: "2026-05-30T16:00:00Z",
    messages: [
      {
        id: "m1",
        senderId: "system",
        content: "Alex expressed interest in “Mid-Century Walnut Sofa”.",
        createdAt: "2026-05-30T15:00:00Z",
      },
      {
        id: "m2",
        senderId: "u_me",
        content: "Love this sofa. Is the scuff noticeable in person?",
        createdAt: "2026-05-30T15:05:00Z",
      },
      {
        id: "m3",
        senderId: "u_sam",
        content: "Barely — it's on the back panel against the wall. Happy to send more photos.",
        createdAt: "2026-05-30T16:00:00Z",
      },
    ],
  },
];

export const transactions: Transaction[] = [
  {
    id: "t_books_done",
    listingId: "l_books",
    buyerId: "u_jordan",
    sellerId: "u_me",
    nonprofitId: "n_readdfw",
    amountCents: 4500,
    status: "completed",
    buyerCode: "4F9K",
    sellerCode: "7Q2M",
    buyerConfirmed: true,
    sellerConfirmed: true,
    createdAt: "2026-05-20T12:00:00Z",
  },
  {
    id: "t_camera_held",
    listingId: "l_camera",
    buyerId: "u_me",
    sellerId: "u_jordan",
    nonprofitId: "n_readdfw",
    amountCents: 20000,
    status: "payment_held",
    buyerCode: "8XJ2",
    sellerCode: "K3PD",
    buyerConfirmed: false,
    sellerConfirmed: false,
    createdAt: "2026-06-01T10:25:00Z",
  },
  {
    id: "t_desk_buyerc",
    listingId: "l_desk",
    buyerId: "u_maya",
    sellerId: "u_sam",
    nonprofitId: "n_green",
    amountCents: 26000,
    status: "buyer_confirmed",
    buyerCode: "QW19",
    sellerCode: "ZT4R",
    buyerConfirmed: true,
    sellerConfirmed: false,
    createdAt: "2026-05-31T09:00:00Z",
  },
  {
    id: "t_guitar_disp",
    listingId: "l_guitar",
    buyerId: "u_sam",
    sellerId: "u_maya",
    nonprofitId: "n_arts",
    amountCents: 14000,
    status: "disputed",
    buyerCode: "LM77",
    sellerCode: "BV20",
    buyerConfirmed: false,
    sellerConfirmed: false,
    createdAt: "2026-05-29T14:00:00Z",
  },
];

export const reports: Report[] = [
  {
    id: "r1",
    target: "listing",
    targetLabel: "“Designer handbag — authentic” by u_unknown",
    reason: "Possible counterfeit goods",
    reporterId: "u_maya",
    status: "open",
    createdAt: "2026-05-31T20:00:00Z",
  },
  {
    id: "r2",
    target: "user",
    targetLabel: "u_spam_account",
    reason: "Scam attempt — asked to pay off-platform",
    reporterId: "u_sam",
    status: "open",
    createdAt: "2026-05-30T18:30:00Z",
  },
  {
    id: "r3",
    target: "transaction",
    targetLabel: "Guitar pickup (t_guitar_disp)",
    reason: "Item not as described",
    reporterId: "u_sam",
    status: "open",
    createdAt: "2026-05-29T15:00:00Z",
  },
];

export const notifications: AppNotification[] = [
  {
    id: "no1",
    kind: "message",
    title: "New message from Jordan",
    body: "Works for me. I'll mark it reserved for you.",
    createdAt: "2026-06-01T10:20:00Z",
    read: false,
    href: "/messages/c_camera",
  },
  {
    id: "no2",
    kind: "payment",
    title: "Payment held",
    body: "Your $200 is securely held for the Canon AE-1.",
    createdAt: "2026-06-01T10:25:00Z",
    read: false,
    href: "/transactions/t_camera_held",
  },
  {
    id: "no3",
    kind: "confirmation",
    title: "Donation completed",
    body: "$45 was sent to Read DFW. Thank you!",
    createdAt: "2026-05-20T13:00:00Z",
    read: true,
    href: "/transactions/t_books_done",
  },
];

export function getUser(id: string): User | undefined {
  return users.find((u) => u.id === id);
}
export function getNonprofit(id: string): Nonprofit | undefined {
  return nonprofits.find((n) => n.id === id);
}
export function getListing(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}
export function getChat(id: string): Chat | undefined {
  return chats.find((c) => c.id === id);
}
export function getTransaction(id: string): Transaction | undefined {
  return transactions.find((t) => t.id === id);
}
export function getListingNonprofit(listing: Listing): Nonprofit | undefined {
  return getNonprofit(listing.nonprofitId);
}

export const platformStats = {
  donatedCents: 482000,
  transactions: 312,
  nonprofits: 18,
  members: 740,
};
